
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
  dubizzle-e2e-tests:
    jobs:
      - cypress/run
          e2e-dubizzle-automated-tests
          steps:
            - checkout
            - run: node --version
        
# jobs:
#   - cypress/run
#     e2e-dubizzle-mena-tests
#         # docker:
#         #   - image: circleci/node:14
#     steps:
#       - checkout
#       - run: node --version
#         - run:
#             name: Install dependencies
#             command: npm install
#         - run:
#             name: Dubizzle tests
#             command: npx cypress run

