version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: 'e2e_dubizzle-tests'
          store_artifacts: true
          
  daily-run-workflow:
    triggers:
      - schedule:
          # Every day, at 5:30pm PK time.
          cron: "30 1 * * *"
          filters:
            branches:
              only:
                - stage
    jobs:
      - cypress/run:
          name: 'e2e_scheduled_dubizzle-tests'
