version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "Cypress" orb
          name: Cypress Run
          executor: cypress/base
          steps:
            - checkout
            - run:
                name: Set Environment Variables
                command: echo "export MY_URL='https://www.dubizzle.com.eg/en/'" >> $BASH_ENV
            - cypress/run:
                start-command: 'npx cypress run --env base_url="$MY_URL"'
          env:
            MY_URL: "https://www.dubizzle.com.eg/en/"
          
  daily-scheduled-run:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          name: Cypress Run
          executor: cypress/base
          steps:
            - checkout
            - run:
                name: Set Environment Variables
                command: echo "export MY_URL='https://www.dubizzle.com.eg/en/'" >> $BASH_ENV
            - cypress/run:
                start-command: 'npx cypress run --env base_url="$MY_URL"'
          # start-command: 'npx cypress run --env base_url="$MY_URL"'
          # env:
          #   MY_URL: "https://www.dubizzle.com.eg/en/"
          # --env MY_URL="https://www.dubizzle.com.eg/en/"
