version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
workflows:
  dubizzle:
    jobs:
    - cypress/run: # "run" job comes from "Cypress" orb
        environment:
          BASE_URL:BASE_URL
        start-command: 'npx cypress run'
          
  daily-scheduled-run:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          name: dubizzle tests
          start-command: 'npx cypress run'
          # --env MY_URL="https://www.dubizzle.com.eg/en/"
