version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
jobs:
  e2e-automated-tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Dubizzle tests
          command: npx cypress run

workflows:
  version: 2
  dubizzle-e2e-tests:
    jobs:
      - e2e-automated-tests
